### PR TITLE
Update Repository (iOS only)

### PR DESCRIPTION
**Pull request by charlieforward9**

### CODE REVIEW

**Comment by charlieforward9** [comment]
@JaeHeee I sent you a LinkedIn connection. Please contact me!

**Comment by JaeHeee** [comment]
Hello, @charlieforward9
Could you resolve conficts?🙏
If the conflict is resolved, I'll merge!

**Comment by charlieforward9** [comment]
@JaeHeee I cleaned it up!.

Looking forward to getting this merged. Been a while! Thanks.

**Comment by JaeHeee** [comment]
Thank you 🙏 @charlieforward9

**Pull request merged**
